[project]
name = "langgraph-customer-support"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chittaksh Khadse", email = "khadse.chittaksh@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
langgraph-customer-support = "langgraph_customer_support:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
